### ISSUE TITLE
Removed from chrome store?

### ISSUE THREAD

**Issue by kathyfan** [ktsn/mirror-tube#1]
Hi, just wanted to ask about the current status! This extension doesn't seem to work anymore/also does not appear in the chrome store anymore. It would be great to have it back. Thanks!

**Comment by ktsn** [comment]
Because the extension does not work on some environment and chrome web store warns me about violation of Program policy because of it. Since I have no time to fix the issue, I simply removed it from the store.

**Comment by kathyfan** [comment]
I see, thanks for the update!
